name: Rebuild :db container from current repository content
on:
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build DB
        run: |
          ./build.sh
      - name: Upload updated DB
        uses: actions/upload-artifact@v4
        with:
          name: cve.db
          path: cve.db
          retention-days: 15
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: scmanjarrez/cvescanner:db,scmanjarrez/cvescanner:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
